разметка html
htmlacademy-htmlcss/559895-nerds-30 pull request #2
Opened 2021-01-23 21:36 UTC by bogman4ik

2021-01-24 16:50 UTC, a-omarova commented on index.html
> +    </section>
Тут как-то странно получается - у тебя сначала идет пагинация слайдера, а потом отдельной секцией текст внутри слайдера. С такой версткой во первых эти блоки по отдельности плохо тянут на секции, во вторых будет очень сложно это стилизовать, в третьих нет картинки.

Скоре тут должно получится так что слайдер это одна большая секция внутри которой список со слайдами - текст и картинка, а после списка - блок с пагинацией.

2021-01-24 16:50 UTC, a-omarova commented on index.html
> +    </section>
Еще имей в виду что все три слайда должны быть в верстке. В макете они есть.

2021-01-24 16:50 UTC, a-omarova commented on index.html
> +          </p>
тег p внутри li здесь избыточен. Одна строка не тянет на параграф и выглядит как лишняя обертка

2021-01-24 16:50 UTC, a-omarova commented on index.html
> +    </section>
В этой секции 2 блока - о студии и статистика. их надо обернуть в контейнер (div) чтобы потом это можно было стилизовать. Плюс так ты их разделяешь по смыслу

2021-01-24 16:50 UTC, a-omarova commented on index.html
> +      </table>
То что ты сверстал здесь таблицей не ошибкой но имхо это слишком простой блок чтоб верстать его таблицей. Сделаешь себе жизнь проще если сверстаешь его просто дивами :)

2021-01-24 16:50 UTC, a-omarova commented on index.html
> +    </section>
это все должно быть в одной секции

2021-01-24 16:50 UTC, a-omarova commented on index.html
> +  </section>
кажется этот блок потерялся :)

2021-01-24 16:50 UTC, a-omarova commented on index.html
> +      <a href="tel:+78122757575">+7 (812) 275-75-75</a>
нет кнопки напишите нам

2021-01-24 16:50 UTC, a-omarova commented on catalog.html
> +                        <img src="https://via.placeholder.com/150x100" alt="Правый ползунок" width="20" height="23">
тут картинки не нужны слайдер будет стилизоваться по-другому. Здесь должен быть блок в котором есть блок для полосы (пока только одной - зеленой) и два блока для кружков

2021-01-24 16:50 UTC, a-omarova commented on catalog.html
> +                            <input id="adaptive" type="radio" name="option" value="" checked disabled>
А почему этот инпут disabled?

2021-01-24 16:50 UTC, a-omarova commented on catalog.html
> +                <section>
Кажется эта обертка тут лишняя. form будет достаточно

2021-01-24 16:50 UTC, a-omarova commented on catalog.html
> +                            <input type="checkbox" name="slider" id="slider" checked disabled>
здесь тоже вопрос зачем disabled

2021-01-24 16:50 UTC, a-omarova commented on catalog.html
> +        <h2>Наши партнеры</h2>
Здесь это список шаблонов а не партнеры_

2021-01-24 16:50 UTC, a-omarova commented on catalog.html
> +        </ul>
Это будут не ссылки а именно кнопки

2021-01-24 16:50 UTC, a-omarova commented on catalog.html
> +        </p>
здесь тег p не подходит по смыслу.

2021-01-24 16:50 UTC, a-omarova commented on catalog.html
> +        <b>СОРТИРОВКА</b>
Опечатка - в макете "сортировать"

2021-01-24 16:50 UTC, a-omarova commented on catalog.html
> +      </footer>
Ошибки указала в index.html

2021-01-24 16:50 UTC, a-omarova commented on catalog.html
> +              <li> <a href="blank.html">корзинка</a></li>
Опечатка)

2021-01-24 16:50 UTC, a-omarova commented on index.html
> +        <li> <a href="blank.html">корзинка</a></li>
Опечатка)

2021-02-01 19:44 UTC, bogman4ik commented on index.html
> +    </section>
не могу проще написать

2021-02-01 19:45 UTC, bogman4ik commented on index.html
> +      </table>
не могу понять как проще написать

2021-02-01 19:47 UTC, bogman4ik commented on index.html
> +    </section>
у меня в макете они почему все одинаковы,  так должно быть?

2021-02-01 19:49 UTC, bogman4ik commented on index.html
> +    </section>
сверстать я их могу меня смущает что в макете они почему то все три слайда одинаковы,
 так должно быть?

2021-02-01 19:56 UTC, bogman4ik commented on index.html
> +    </section>
сверстать я их могу. Меня смущает что в макете почему то все три слайда одинаковы,
так должно быть?

2021-02-02 21:29 UTC, a-omarova requested changes

2021-02-02 21:29 UTC, a-omarova commented on catalog.html
> +        <section>
вот эти две секции нужно будет поместить в один div чтобы это все можно было потом позиционировать

2021-02-02 21:29 UTC, a-omarova commented on catalog.html
> +                        <span>9 900 руб</span>
это тоже нужно поместить в отдельный блок

2021-02-02 21:29 UTC, a-omarova commented on catalog.html
> +        </section>
заголовок и секция тоже должны быть в одном блоке

2021-02-02 21:29 UTC, a-omarova commented on catalog.html
> +            <span>тел. +7 (812) 275-75-75</span>
телефоны нужно оборачивать в ссылки с атрибутом href которая содержит протокол tel. Например href="tel:4444444444"

2021-02-02 21:29 UTC, a-omarova commented on index.html
> +      <div class= slide-first>
тут у класса пропали кавычки

2021-02-02 21:29 UTC, a-omarova commented on index.html
> +      <div class="slide second">
а тут пропал дефис)

2021-02-02 21:29 UTC, a-omarova commented on index.html
> +      <div class="slide third">
и тут пропал дефис)

2021-02-02 21:29 UTC, a-omarova commented on index.html
> +      </table>
У тебя получится общий контейнер, внутри которого еще три контейнера. Ну а собственно внутри каждого из трех контейнеров блок с цифрой и блок с текстом)

2021-02-07 08:49 UTC, merged